language: generic
sudo: required
services:  
  - docker

before install:
  - docker build -t s-azeem-zaidi/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true s-azeem-zaidi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-254873692033"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY