language: generic
sudo: required
services:  
  - docker

before install:
  - docker build -t azeem-zaidi/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true azeem-zaidi/docker-react npm run test